services:

  postgres:
    image: postgres:16

    container_name: reservago_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - reservago_postgres_data:/var/lib/postgresql/data

    networks:
      - reservago_network

volumes:

  reservago_postgres_data:

networks:

  reservago_network:
    driver: bridge